# Generated by Django 5.1.4 on 2025-01-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peserta', models.CharField(editable=False, max_length=4, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('jenis_kelamin', models.CharField(choices=[('laki laki', 'Laki Laki'), ('perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('alamat', models.CharField(max_length=80)),
                ('kota', models.CharField(max_length=80)),
                ('provinsi', models.CharField(max_length=80)),
                ('warga_negara', models.CharField(choices=[('indonesia', 'Indonesia'), ('malaysia', 'Malaysia'), ('singapura', 'Singapura'), ('lainya', 'Lainya')], max_length=20)),
                ('gol_darah', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('ab', 'AB'), ('o', 'O'), ('tidak diketahui', 'Tidak Diketahui')], max_length=15)),
                ('jenis_id', models.CharField(choices=[('ktp', 'KTP'), ('sim', 'SIM'), ('kartu pelajar', 'Kartu Pelajar'), ('passport', 'Passport')], max_length=15)),
                ('no_id', models.CharField(max_length=80)),
                ('f_id', models.FileField(upload_to='ids/')),
                ('kategori', models.CharField(choices=[('umum', 'Umum (dibawah 45 tahun)'), ('master', 'Master (diatas 45 tahun)')], max_length=45)),
                ('kontak_darurat', models.CharField(max_length=80)),
                ('no_kontak_darurat', models.CharField(max_length=80)),
                ('riwayat_penyakit_jantung', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('riwayat_penyakit_hipertensi', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('riwayat_penyakit_kronik', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('riwayat_penyakit_epilepsi', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('riwayat_penyakit_asma', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('memiliki_asuransi', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('riwayat_alergi_obat', models.IntegerField(choices=[(1, 'Ya'), (2, 'Tidak')])),
                ('alergi', models.CharField(blank=True, max_length=80)),
                ('bib', models.CharField(max_length=80)),
                ('size_baju', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=5)),
                ('f_pembayaran', models.FileField(upload_to='payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
